version: '3.8'

services:
  mongodb:
    container_name: mongo_dev
    image: mongo
    ports:
      - '27017:27017'

  mongo-seed:
    container_name: mongo_seed
    build: ./FAIR_tool_discoverer_backend/database/mongo-seed
    depends_on:
      - 'mongodb'
  
  prepare-data:
    container_name: prepare_data
    build: ./FAIR_tool_discoverer_backend/database/prepare-data
    depends_on:
      - 'mongo-seed'
  
  back-end:
    image: wp3fairtooling/tools_discoverer_backend 
    restart: unless-stopped
    depends_on:
      - 'mongodb'

  front-end:
    image: wp3fairtooling/tools_discoverer_fe_dev
    restart: unless-stopped
    depends_on:
      - 'back-end' 
    ports:
      - '8080:80'